require_relative './config/environment'
require 'sinatra/activerecord/rake'
# rake db:create              # Creates the database from DATABASE_URL or con...
# rake db:create_migration    # Create a migration (parameters: NAME, VERSION)
# rake db:drop                # Drops the database from DATABASE_URL or confi...
# rake db:environment:set     # Set the environment value for the database
# rake db:fixtures:load       # Loads fixtures into the current environment's...
# rake db:migrate             # Migrate the database (options: VERSION=x, VER...             
# rake db:migrate:status      # Display status of migrations
# rake db:rollback            # Rolls the schema back to the previous version...
# rake db:schema:cache:clear  # Clears a db/schema_cache.dump file
# rake db:schema:cache:dump   # Creates a db/schema_cache.dump file
# rake db:schema:dump         # Creates a db/schema.rb file that is portable ...
# rake db:schema:load         # Loads a schema.rb file into the database
# rake db:seed                # Loads the seed data from db/seeds.rb
# rake db:setup               # Creates the database, loads the schema, and i...
# rake db:structure:dump      # Dumps the database structure to db/structure.sql
# rake db:structure:load      # Recreates the databases from the structure.sq...
# rake db:version             # Retrieves the current schema version number

task :console do
  require 'irb'
  ARGV.clear
  IRB.start
end
